### PR TITLE
Particles

### PR DESCRIPTION
**Pull request by dpzwick**
Added particles files. There are some short tests in the short tests folder, but they are mainly meant for people using particles.

### CODE REVIEW

**Comment by dpzwick** [comment]
These are more examples for people wanting to use particles in the future.
I don't expect it to ever get folded in to UFCCMT/master, it was just a
holding place for some examples for now.

There are three cases in there. In setting up particles for Bertrand, the
uniform_flow or exp_waves case would work well as examples. Let me know if
you have any questions. I won't be there today, but will be in tomrrow.

Best wishes,
David

David Zwick

**Comment by hackljf** [comment]
What I think we will do is have you write an actual short_test and also
move the rest of your examples into a dedicated branch of UFCCMT/NekExamples


Argonne is making me add my stuff to NekTests.py in NekExamples, but I
think we can relax that requirement for UFCCMT usage. I do believe that
short_tests should serve a very specific purpose beyond tutorial use (that
is, regression testing), and you do need one

**Comment by dpzwick** [comment]
I will cancel the pull request and remove the examples and add that to the
UFCCMT/NekExamples folder. Thank you.

David Zwick

**Comment by hackljf** [comment]
You can do that. You should know that I am still working on the last major
hurdle of getting CMT-nek's shock waves into NekExamples. Once that is done
we will want to have your particle stuff in an up-to-date branch of
UFCCMT/NekExamples.

Great work David. It may have to wait until tomorrow morning for me to
catch up.

**Pull request closed without merging**
